PROPUBLICA_BASE = "https://api.propublica.org/congress/"
PROPUBLICA_INDEX = 0
PROPUBLICA_VER = "v1/"

CONGRESS_HOUSE_MIN = 102
CONGRESS_HOUSE_MAX = 117

CONGRESS_SENATE_MIN = 80
CONGRESS_SENATE_MAX = 117

CONGRESS_MEMBER = {
    "house": [CONGRESS_HOUSE_MIN, CONGRESS_HOUSE_MAX + 1], 
    "senate": [CONGRESS_SENATE_MIN, CONGRESS_SENATE_MAX + 1],
}

COMMITTEE_MIN = 105
COMMITTEE_MAX = 117

CONGRESS_COMMITTEE = [COMMITTEE_MIN, COMMITTEE_MAX]

CONGRESS_SENATE = "senate"
CONGRESS_HOUSE = "house"
CONGRESS_JOINT = "joint"

